import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Cursor from "@/app/_components/cursor";
import {roboto, roboto_mono} from "@/app/_components/font";
import MenuButton from "@/app/_components/menu_button";
import React from "react";
import Script from "next/script";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className + "overflow-hidden bg-[#0d0d0d]"} >
      <MenuButton />
        {children}
        <Cursor />
      </body>
      <Script src="https://cdn.jsdelivr.net/gh/cnumr/ecoindex_badge@3/assets/js/ecoindex-badge.js" defer></Script>
    </html>
  );
}
